/* This file was generated by the invn.pysonic Python package. It may need some
 * manual adjustment to work correctly within your application. In particular,
 * you may need to modify the includes if you have some non-standard include
 * paths or if you're using a version of soniclib before the invn namespace was
 * added.
 *
 * We also assume that the required algorithm header icu_algo_format.h is provided
 * at the include path <invn/soniclib/sensor_fw/icu_gpt>. In the case of
 * an official TDK Invensense release, the plugin support package for the
 * algorithm contains the header at this location.
 *
 * Generated from: measurement_config.json
 *
 * invn.pysonic version: 4.35.1
 */

#include <invn/soniclib/details/shasta/shasta_external_regs.h>  // general ICU ASIC definitions
#include <invn/soniclib/sensor_fw/icu_gpt/icu_algo_format.h>  // algorithm specific definitions
#include <invn/soniclib/soniclib.h>

measurement_queue_t measurement_config_queue = {
    .intconfig=0, 
    .meas_start=0, 
    .meas_stop=0, 
    .current_meas=0, 
    .trigsrc=2, 
    .reserved=0, 
    .meas={
        {
            .trx_inst={
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=512
                }, 
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=9
                },
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=9
                }, 
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=9
                }, 
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=9
                }, 
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=9
                }, 
                {
                    .cmd_config=14370, 
                    .length=128
                },  
                {
                    .cmd_config=42, 
                    .length=21632
                }, 
                {
                    .cmd_config=3, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }
            }, 
            .meas_period=0, 
            .odr=5, 
            .meas_flags=0
        }, 
        {
            .trx_inst={
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=512
                }, 
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=9
                },
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=9
                }, 
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=9
                }, 
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=9
                }, 
                {
                    // .cmd_config=32, 
                    .cmd_config=32, 
                    .length=9
                }, 
                {
                    .cmd_config=14370, 
                    .length=128
                },  
                {
                    .cmd_config=42, 
                    .length=21632
                }, 
                {
                    .cmd_config=3, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }, 
                {
                    .cmd_config=0, 
                    .length=0
                }
            }, 
            .meas_period=0, 
            .odr=5, 
            .meas_flags=0
        }
    }
};


// measurement_queue_t measurement_config_queue = {
//     .intconfig=0, 
//     .meas_start=0, 
//     .meas_stop=0, 
//     .current_meas=0, 
//     .trigsrc=2, 
//     .reserved=0, 
//     .meas={
//         {
//             .trx_inst={
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=33569, 
//                     .length=512
//                 }, 
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=1057, 
//                     .length=9
//                 },
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=289, 
//                     .length=9
//                 }, 
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=4385, 
//                     .length=9
//                 }, 
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=4385, 
//                     .length=9
//                 }, 
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=4385, 
//                     .length=9
//                 }, 
//                 {
//                     .cmd_config=14370, 
//                     .length=128
//                 },  
//                 {
//                     .cmd_config=42, 
//                     .length=21632
//                 }, 
//                 {
//                     .cmd_config=3, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }
//             }, 
//             .meas_period=0, 
//             .odr=5, 
//             .meas_flags=0
//         }, 
//         {
//             .trx_inst={
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=33569, 
//                     .length=512
//                 }, 
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=1057, 
//                     .length=9
//                 },
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=289, 
//                     .length=9
//                 }, 
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=4385, 
//                     .length=9
//                 }, 
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=4385, 
//                     .length=9
//                 }, 
//                 {
//                     // .cmd_config=32, 
//                     .cmd_config=4385, 
//                     .length=9
//                 }, 
//                 {
//                     .cmd_config=14370, 
//                     .length=128
//                 },  
//                 {
//                     .cmd_config=42, 
//                     .length=21632
//                 }, 
//                 {
//                     .cmd_config=3, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }, 
//                 {
//                     .cmd_config=0, 
//                     .length=0
//                 }
//             }, 
//             .meas_period=0, 
//             .odr=5, 
//             .meas_flags=0
//         }
//     }
// };

InvnAlgoRangeFinderConfig measurement_config_cfg  = {
    .meas_cfg={
        {
            .ringdown_cancel_samples=20, 
            .static_target_samples=0, 
            .thresholds={
                .stop_index={
                    20, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                }, 
                .threshold={
                    40000, 
                    6000, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                }
            }, 
            .num_ranges=2, 
            .iq_output_format=0, 
            .filter_update_modulo=0, 
            .reserved=0
        }, 
        {
            .ringdown_cancel_samples=20, 
            .static_target_samples=0, 
            .thresholds={
                .stop_index={
                    20, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                }, 
                .threshold={
                    40000, 
                    6000, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0, 
                    0
                }
            }, 
            .num_ranges=3, 
            .iq_output_format=0, 
            .filter_update_modulo=0, 
            .reserved=0
        }
    }
};
